### ISSUE TITLE
Add headshots for everyone

### ISSUE THREAD

**Issue by garethellis0** [UBC-Snowbots/UBC-Snowbots.github.io#17]

**Comment by garethellis0** [comment]
@SimonJinaphant Any chance we can add some sort of "Who We Are" section to the website, with headshots, names, faculties, and position on the team? (probably subdivided by sub-team). Let me know if you need a list and I can get that for you.

**Comment by SimonJinaphant** [comment]
I took out the roster temp. until the headshots for this year arrives. If you need a simpler roster in the mean time with just the name of people then send me the list
