### ISSUE TITLE
Adhere to UBC Trademark and Logo 

### ISSUE THREAD

**Issue by ValRat** [UBC-Snowbots/UBC-Snowbots.github.io#46]
Hello,

The Brand and Marketing team at the University of British Columbia (UBC) is working on a project to identify improper usage of UBC trademarks and logos online. 

We have found that the incorrect logo for UBC is being used on this website: http://snowbots.ca/. 

The image URL is as follows: http://snowbots.ca/images/sponsor_logo/ubcapsc-logo.png. 

As the logo is a trademark of the University of British Columbia, we kindly request that you either remove the old UBC logos being used on this website or replace them with the correct UBC logo.

You can download UBC Logo assets as well as instructions on how to use them correctly on the official UBC Brand website:
http://brand.ubc.ca/brand-toolkit/templates-and-assets/logos-signatures-and-visual-identity-assets/ 

Please let us know once updated.

Sincerely,
UBC Brand and Marketing

**Comment by SimonJinaphant** [comment]
#47 

Work-around for now
